### ISSUE TITLE
Issue with 21w37a snapshot on waterfall

### ISSUE THREAD

**Issue by ScriptJunkieMC** [ME1312/VanillaCord#10]
I have attempted to build and run a snapshot as a test (latest 21w37a). I see in your notes you say added support for velocity ip-forwarding. Does this mean this now only supports velocity? I hooked mine to bungee and waterfall to run some tests and it shows nothing in the log on the snapshot server when attempting the connection.

**Comment by ScriptJunkieMC** [comment]
Main issue is that snapshot support doesnt work i assume. Just want to confirm about the velocity / waterfall/bungeecord compatibility first before really digging into any other core issue that could be causing this.

**Comment by ScriptJunkieMC** [comment]
``Script runs the compile just fine:

`C:\_apps\vanillacord>C:\Progra~1\Java\jdk-16.0.1\bin\java -jar VanillaCord.jar 21W37A
VanillaCord 1.7
Searching versions
Found Minecraft Server 21w37a
Loading
Found the login listener in acq.class
Found the handshake listener in acp.class
Hooking
Generating helper classes
Exporting patched jarfile`


`Proxy sees me trying to attempt the connection to the vanillacord host:

17:46:48 [INFO] [ScriptJunkie] <-> ServerConnector [moana11] has connected
17:46:48 [INFO] [ScriptJunkie] <-> ServerConnector [moana11] has disconnected
`

No output in vanillacord server log though.

**Comment by ME1312** [comment]
The first order of business when reporting an issue regarding snapshots is to find a proxy that was willing to support them in the first place. If you happened to be using one here, drop me a link.

**Comment by ScriptJunkieMC** [comment]
Gotcha do you have a tested tried and true one that you have used? I used to use snapshot waterfall but they have removed those at this point and now rely on viaversion to handle the support. So technically all should support when viaversion is applied.

**Comment by ME1312** [comment]
I don't think ViaVersion is applicable here. We're trying to connect a 1.18 client to a 1.18 server in this case. We are not connecting a 1.18 user to a __1.17__ server. So, we're going to need a fork that can actually forward this protocol.

The proxy that I used back then has not yet been updated, it seems.

**Comment by ScriptJunkieMC** [comment]
cool thanks. yeah that seems right. was thinking backwards lol.
