### ISSUE TITLE
Error while patching 1.18-pre1: packager is not able to detect downloaded server jar

### ISSUE THREAD

**Issue by quiquelhappy** [ME1312/VanillaCord#12]
executing `java -jar VanillaCord.jar 1.18-pre1` results in:
```
VanillaCord 1.8
Searching versions
Found Minecraft Server 1.18-pre1
Running the self-extracting server bundle
Cannot locate server file, giving up
```

line: https://github.com/ME1312/VanillaCord/blob/master/src/main/java/uk/co/thinkofdeath/vanillacord/packager/BEv1.java#L82

**Comment by ME1312** [comment]
There seems to be a discrepancy between the requested version name and the actual version name. `1.18-pre1` was requested, but `1.18 Pre-release 1` was extracted. Luckily, you only get 1 version per bundle, so detecting the actual name isn't hard.

This should be resolved in the latest VanillaCord build.

**Comment by quiquelhappy** [comment]
seems to be resolved, thanks for the quick response. have an amazing day!
