### ISSUE TITLE
[Feature Idea] Possibility to use BungeeGuard instead of Velocity Modern Forwarding

### ISSUE THREAD

**Issue by Mrredstone5230** [ME1312/VanillaCord#18]
Everything's in the title. (I said "instead" but having both option available when patching the jar would be nice) Would it be possible?

**Comment by ME1312** [comment]
Well, it looks like BungeeGuard forwarding is design-compatible with normal IP forwarding, so you should be able to login to a VanillaCord server just fine as-is. That said, some changes will be needed to actually check for and make use of the provided token.

**Comment by ME1312** [comment]
As of that commit, it should now be possible to specify BungeeGuard tokens for VanillaCord to validate using `seecret.txt`.

`seecret.txt` isn't new to those using [modern IP forwarding](https://github.com/ME1312/VanillaCord/blob/master/src/main/java/uk/co/thinkofdeath/vanillacord/helper/VelocityHelper.java#L122-L127), but it is new to those using ["legacy" IP forwarding](https://github.com/ME1312/VanillaCord/blob/master/src/main/java/uk/co/thinkofdeath/vanillacord/helper/BungeeHelper.java#L89-L94). You can learn more about it by clicking the relevant link in the last sentence.

**Comment by Mrredstone5230** [comment]
Do you have to directly execute Pather.class ? I don't understand how seecret.txt is supposed to be generated.

**Comment by ME1312** [comment]
As "BungeeCord" and "BungeeGuard" use the same method for forwarding information, the patch process is the same as it was before. `seecret.txt` is a config file that appears after joining a VanillaCord server.

**Comment by Mrredstone5230** [comment]
Unfortunately, it didn't quite work. If you but an invalid token from bungee, the player will still be able to connect. Made a quick patch for it.
