### ISSUE TITLE
java.lang.IllegalArgumentException: Unexpected packet received during server login process!

### ISSUE THREAD

**Issue by DmitryRendov** [ME1312/VanillaCord#2]
### What Happened
Some users couldn't connect to vanilla server via Bungee due to such errors:
Vanilla error - https://pastebin.com/nXCxeL4p
Bungee error - https://pastebin.com/vmDHpqtb
at the same time some others can...

### How It Happened
Bungee with Spigot as Lobby and Vanilla sub-server with ip forwarding is on

### Additional Information
idk, possible related issue https://github.com/SpigotMC/BungeeCord/issues/2518

**Comment by ME1312** [comment]
This issue does not show up in my tests [(SubServers build log)](https://pastebin.com/Eyt2BDFg). Following the referenced issue seems to suggest that something (but not minecraft) is connecting to your network and causing issues.
