### ISSUE TITLE
1.21 Error with velocity

### ISSUE THREAD

**Issue by RawrUniversal** [ME1312/VanillaCord#25]
### What Happened
Here you can write about what happened that shouldn't have. If you have any errors in your console related to what happened, you should also paste those here.

```
Time: 2024-06-21 14:50:25
Description: Exception in server tick loop

java.lang.IllegalAccessError: class vanillacord.translation.NamespacedKey tried to access private method 'void akr.<init>(java.lang.String, java.lang.String)' (vanillacord.translation.NamespacedKey and akr are in unnamed module of loader java.net.URLClassLoader @4ccabbaa)
	at vanillacord.translation.NamespacedKey.new(Unknown Source)
	at vanillacord.server.VelocityHelper.<clinit>(VelocityHelper.java:29)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:500)
	at vanillacord.server.VanillaCord.<clinit>(VanillaCord.java:86)
	at apn.e(SourceFile:121)
	at net.minecraft.server.MinecraftServer.y(SourceFile:664)
	at net.minecraft.server.MinecraftServer.a(SourceFile:281)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

### Additional Information
Here you can provide any extra details you may think useful for solving the problem.

**Comment by ME1312** [comment]
Yep, they made the constructor for namespaced keys private. It should be all fixed now.

**Comment by github-nachtschelm** [comment]
Hi everybody,
I just downloaded the latest vanillacord build, had a new mc server patched (1.21) and still run into the problem initially stated.
![image](https://github.com/ME1312/VanillaCord/assets/92056524/7ae6cf31-da35-405a-acff-3b5c29a8880d)
Do I have to update anything else?

Thanks in advance

**Comment by ME1312** [comment]
It would appear that the updated patch hasn't been applied. Can I see your `java --version` and VanillaCord server version?
Both patcher and server for this commit will identify themselves as `VanillaCord 2.0 (24w25a)` on startup.

**Comment by github-nachtschelm** [comment]
Thank you for the swift relpy, @ME1312 .

I'm embarrassed to admit that I'm obviously to dumb to download files.
I didn't realise that wget did not overwrite the existing jar but saved it to jar.1. Thus, I patched the mc server using the older VanillaCord.jar. Thanks to your hint regarding the VanillaCord version I found out.

Thanks again and please forgive me having wasted your time.
