### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by TomerItzko** [ME1312/VanillaCord#26]
can i get some help?
i dont understand how to use it

**Comment by ME1312** [comment]
Well, you pretty much just navigate to the jarfile in your terminal and type `java -jar VanillaCord.jar` followed by one or more version ids as arguments. VanillaCord will download each server to the `in` folder, verify them, patch them, and export them to the `out` folder one at a time. You would then take the files from the `out` folder and run them, configure them further, etc.

You can also use VanillaCord offline by instead typing `java -cp VanillaCord.jar vanillacord.Patcher` followed by one or more pairs of input and output file paths as arguments. This does the same thing without all the downloading and temporary folders.

**Comment by TomerItzko** [comment]
how do i know the version id?

**Comment by ME1312** [comment]
You can find them in Minecraft Launcher under the versions dropdown when editing an installation. They are usually short, contain no spaces, and look like the following:
```
1.19.4
1.19.4-rc3
1.19.4-pre4
23w07a

1.19
1.19-rc2
1.19-pre5
22w16b
22w13oneblockatatime
```
