### ISSUE TITLE
Doesn't allow offline mode proxies to forward to the server.

### ISSUE THREAD

**Issue by TheRedMelon** [ME1312/VanillaCord#3]
Gives:
`19:53:02 [SEVERE] [mattbojh] <-> ServerConnector [lobby] - encountered exception
java.lang.IllegalArgumentException: Unexpected packet received during server login process!
1bb9017b227472616e736c617465223a22646973636f6e6e6563742e67656e65726963526561736f6e222c2277697468223a5b22496e7465726e616c20457863`
when connecting

**Comment by ME1312** [comment]
Duplicate of #2 

This issue has the bit of information I needed attached to it though: the cause. I can confirm this issue does show up in my tests. Still investigating though.

**Comment by ME1312** [comment]
Resolved as of the latest commit to both branches. (be sure to delete the `in` folder if you're using the launcher version!)
