### ISSUE TITLE
args:<version>

### ISSUE THREAD

**Issue by MrCazuela** [ME1312/VanillaCord#5]
hi

When starting server 1.15 with this startup parameter: java -Xms128M -Xmx1024M -jar VanillaCord.jar, I get an error that causes the server to crash, it is as follows: / home / container $ java -Xms128M -Xmx1024M -jar VanillaCord .jar
Args: <version>, I would like to know how to fix it.

**Comment by ME1312** [comment]
VanillaCord is not a server program, but it will help you build one.

To create a VanillaCord patched 1.15 Minecraft Server jar, type the following console command:
```
java -jar VanillaCord.jar 1.15
```
