### ISSUE TITLE
Provide a license for the repository

### ISSUE THREAD

**Issue by DaMarine** [ME1312/VanillaCord#8]
### What Should Be Added
Hi there! Currently this repository has no clear license, and without that GitHub's terms of service state we legally cannot modify the code of this repository in any way, even locally or in a fork: https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license

### Why It Should be Added
For context, I'm interested in tinkering with this in a private GitHub organisation, though the repo would remain private and not be distributed. Other people may like to know the clear terms of how, if at all, we may use this code. Would you consider adding a license to let us know whether this is possible?

### What's The Alternative
No clear license means we do not have the rights to do more than look at the code :)

**Comment by ME1312** [comment]
Is that something I'm allowed to do, I wonder. Aside from that in the launcher app (which now resides in the master branch), the majority of this code is not actually mine &mdash; and I don't want a craftbukkit situation on my hands.

I would now direct you up the chain to the repo's [original maintainer](https://github.com/Thinkofname/vanillacord), but there hasn't been any activity there in years. The best we're probably going to get in this regard is the previous [written consent to continue development](https://github.com/Thinkofname/vanillacord/issues/4#issuecomment-317268315). Whether that permits me to change (or, in this case, add) the license, I don't know.
